### ISSUE TITLE
Determine which otlp exporters to use in examples

### ISSUE THREAD

**Issue by svetlanabrennan** [newrelic/newrelic-opentelemetry-examples#136]
Which otlp exporter should we use - http/proto or grpc?

Once we decide which exporter to use, we can:

- delete one of the JS examples that isn't using the exporter that we selected.
- update the rest of the examples to use the selected exporter (if needed)

**Comment by nrcventura** [comment]
My recommendation is to use the most appropriate one for your ecosystem. 

For example, for the .net agent example, I'm using http/proto because that is the recommendation from that SIG (it works more seamlessly with fewer dependencies to manage). For other languages or uses cases, grpc may be more appropriate.

**Comment by jack-berg** [comment]
If there's not a clear preference, I say we recommend http/proto.
