### ISSUE TITLE
Node.js - add example of equivalent `noticeError` API using OpenTelemetry

### ISSUE THREAD

**Issue by o-alexandrov** [newrelic/newrelic-opentelemetry-examples#168]
## Summary

Based on the [discussion here](https://discuss.newrelic.com/t/node-how-to-invoke-noticeerror-using-an-http-request-w-o-an-agent/188740), please add an example of equivalent `noticeError` API using OpenTelemetry w/ New Relic.

## Additional context

Exception handling is one of the most frequent features devs build.
To not require devs to create the same solution over and over, you could create an example, letting companies to adopt your service easier.

**Comment by o-alexandrov** [comment]
@martinkuba thanks to your wonderful additions in https://github.com/open-telemetry/opentelemetry-js/pull/3117, are you by any chance considering to help us here?

**Comment by martinkuba** [comment]
Hi, Olzhas! Are you looking to use the OpenTelemetry JS SDK or make an HTTP call to the NR OTLP endpoint directly? If the latter, I could help now. Regarding the former, the Javascript SDK does not have an implementation of the Logs API yet. I am working on that now, but it will take some time to get that merged and released. Also, with either of these options, you will end up with a New Relic `Log` event with the [exception attributes](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/exceptions.md), not a TransactionError event. Is that acceptable to you?

**Comment by o-alexandrov** [comment]
Thank you for the reply.
Unfortunately, `Log` event is not a good alternative, as afaik it won't end up in the `Errors inbox`.

If possible, please kindly share whether `ability to add a TransactionError event` is on the roadmap for OTLP endpoint (either using HTTP or w/ OpenTelemetry JS SDK)

**Comment by nrcventura** [comment]
`TransactionError` is a New Relic specific concept. The closest thing that I'm aware of is when a Span is flagged as having an error. It looks like this can be done in otel-js with code similar to the following:

```javascript
  span.setStatus({ code: SpanStatusCode.ERROR, message });
  span.recordException(error);
```
What I don't remember is if Errors Inbox will capture all spans that have a status of `error` or if it only captures the `server` spans that have a status of `error`.

**Comment by alanwest** [comment]
Hello @o-alexandrov

> are you (NewRelic) by any chance considering to help us here?

At this point in time we have kept the scope of this examples repository narrow ([outlined here](https://github.com/newrelic/newrelic-opentelemetry-examples#new-relic-opentelemetry-examples)) - essentially how to configure the OTLP exporter to ship metrics, logs, traces to New Relic in a number of languages.

That said, we do have plans to expand our scope to better highlight how to use New Relic features like Errors Inbox. We're doing so in coordination with our documentation team. Using Errors Inbox with OpenTelemetry tooling is [documented here](https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/view-your-data/opentelemetry-errors-inbox-page#unique-fingerprints). Of course, the thing that's missing are simple examples demonstrating how to achieve what we've documented there.

We're working with our docs team to better connect the dots from our OpenTelemetry documentation to examples within this repository. @rhetoric101 @reese-lee @rkbodenner

In the meantime, the information @nrcventura shared regarding Errors Inbox should work for you. And to clarify, Errors Inbox, currently only counts [spans of kind](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#spankind) `server` or `consumer`. This is because `server` or `consumer` spans are considered "entry-point" spans for a process. Furthermore, counting errors in Errors Inbox in this way corresponds to the method we use to calculate error rate on the [Summary View](https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/view-your-data/opentelemetry-summary-page) of a service.
