### ISSUE TITLE
Cannot show logs in new relic dashboard when running logs-in-context-log4j2

### ISSUE THREAD

**Issue by TDtianzhenjiu** [newrelic/newrelic-opentelemetry-examples#416]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

After configuring my newrelic configurations, call the ping endpoint in my local

while I can see the transaction section  has this` /ping` endpoint
I cannot see any logs in the trace

The pic shows the empty logs:

<img width="1311" alt="截屏2023-08-13 16 38 52" src="https://github.com/newrelic/newrelic-opentelemetry-examples/assets/79951542/726e67a2-2401-4d66-8548-b4129358becc">

## Steps to Reproduce

1. configure newrelic configurations
2. start logs-in-context-log4j2 in my local
3. Checking the newrelic dashboard

## Expected Behavior

Should see some log messages in the dashboard

## Your Environment

JDK: 17
OS: MAC M1

**Comment by jack-berg** [comment]
Hi @TDtianzhenjiu! I actually did some work recently to adjust this example to run purely with docker (i.e. no requirement to have java installed locally to run). In the process of doing this, I realized that some log records being generated by the app were being rejected because the log bodies were longer than the 4095 character limit New Relic imposes, so the logs were being dropped and generating NrIntegrationErrors. In the process of dockerizing the example, I added a collector processor to truncate log record bodies which are over the limit, which should fix issue you're seeing.

Marking this as closed as I believe its fixed, but please re-open if you give it a try and still don't see the logs.
